App/Models/ErrorViewModel.cs
namespace App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

App/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class ClientController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult MenuCliente()
        {
            return View();
        }
        public IActionResult PerfilCliente()
        {
            return View();
        }
        public IActionResult UpdateUserCliente()
        {
            return View();
        }
        public IActionResult ViewUserFood()
        {
            return View();
        }
        public IActionResult ViewFoodClient()
        {
            return View();
        }
        public IActionResult ViewSpecificFoodClient()
        {
            return View();
        }
    }
}

App/Controllers/CreateUserController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class CreateUserController : Controller
    {
        public IActionResult CreateUser()
        {
            return View();
        }
    }
}

App/Controllers/HomeController.cs
using App.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

App/Controllers/LandingPageController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class LandingPageController : Controller
    {
        public IActionResult LandingPage()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View("~/Views/Client/Login.cshtml");
        }
        public IActionResult CreateUser()
        {
            return View("~/Views/Client/CreateUser.cshtml");
        }
    }
}

App/Controllers/LogInController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class LogInController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

App/Controllers/NutriController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    public class NutriController : Controller
    {
        public IActionResult CreateFood()
        {
            return View();
        }

        public IActionResult UpdateFood()
        {
            return View();
        }
        public IActionResult UpdateUser()
        {
            return View();
        }

        public IActionResult Menu()
        {
            return View();
        }
        public IActionResult ViewFood()
        {
            return View();
        }
        public IActionResult ViewClients()
        {
            return View();
        }
        public IActionResult ViewSpecificFood()
        {
            return View();
        }
        public IActionResult Perfil()
        {
            return View();
        }


    }
}

App/Views/Client/CreateUser.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/CreateUser.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <header class="header">
        <div class="logo">
            <div>
                <img src="../Resources/LogoCompletoBlanco.png" alt="">
            </div>
        </div>
        <nav class="navbar">
            <a href="@Url.Action("Menu", "Nutri")" id="SignIn">Iniciar Sesión</a>
        </nav>
    </header>


    <div class="contenedor">


        <main class="main-content">
            <div class="container-content">
                <h1>Registrate </h1>
                <h2>Por favor llena todos los espacios con la información correspondiente</h2>
                <div class="info-and-photo-container">
                    <div class="register-container">
                        <div class="form-row">
                            <div class="input-container">
                                <label>Nombre</label>
                                <input class="input required" id="txt-name" type="text" name="brand" />
                            </div>
                            <div class="input-container">
                                <label>Apellido</label>
                                <input id="txt-lastName" class="input required" type="text" name="portionHome" />
                            </div>
                            
                        </div>
                        <div class="form-row">
                            <div class="input-container">
                                <label>Cédula</label>
                                <input class="input required" id="txt-cedula" type="text" name="brand" />
                            </div>
                            <div class="input-container">
                                <label>Edad</label>
                                <input id="txt-age" class="input required" type="number" name="excFlour" />
                            </div>
                            
                        </div>
                        <div class="form-row">
                            <div class="input-container">
                                <label>Rol</label>
                                <select class="input required" id="roleType" name="categoryType">
                                    <option id="" value=""></option>
                                    <option id="roleCostumer" value="cliente">Cliente</option>
                                    <option id="roleNutri" value="nutricionista">Nutricionista</option>
                                </select>
                            </div>
                            <div class="input-container">
                                <label>Correo electrónico</label>
                                <input id="text-email" class="input required" type="text" name="exceDairySkim" />
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="input-container">
                                <label>Contraseña</label>
                                <input id="text-password" class="input required" type="password" name="exceDairySkim" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="button">
                    <div class="btn-container">
                        <button id="btn-continue">Continuar</button>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/swal/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/CreateUser.js" asp-append-version="true"></script>
</body>
</html>

App/Views/Client/LogIn.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Login.css">
</head>
<body>
    <div class="container">
        <div class="left-panel">
            <img src="../Resources/img4.jpg" alt="">
        </div>
        <div class="right-panel">
            <img src="../Resources/NegroNoBG.png" alt="">
            <form action="#">
                <div class="input-container">
                    <label for="email">Correo:</label>
                    <input class="required" type="email" id="txt-email" name="email" required>
                </div>
                <div class="input-container">
                    <label for="password">Contraseña:</label>
                    <input class="required" type="password" id="txt-password" name="password" required>
                </div>
                <button id="btnLogin" type="submit">Iniciar Sesión</button>
            </form>
            <a href="@Url.Action("CreateUser", "LandingPage")">Crear cuenta</a>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/swal/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Login.js"></script>
</body>
</html>

App/Views/Client/MenuCliente.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/NutriMenu.css" type="text/css" rel="stylesheet" />

</head>
<body>
    <header class="header">
        <div class="logo">
            <div>
                <img src="../Resources/LogoCompletoBlanco.png" alt="">
            </div>
        </div>

        <nav class="navbar">
            <a href="@Url.Action("ViewUserFood","Client")">Mis Productos</a>
            <a href="@Url.Action("ViewFoodClient","Client")">Lista de Productos</a>
            <a href="@Url.Action("MyPlan","Client")">Mi Plan Nutricional</a>
            <a href="@Url.Action("PerfilCliente","Client")">Mi Perfil</a>
            <a id="logout")">Cerrar Sesión</a>
        </nav>
    </header>
    <div class="main-container">
        <div class="slideshow-container">

            <!-- Full-width images with number and caption text -->
            <div class="mySlides fade">
                <img src="../Resources/Carrusel1.jpg" style="width:100%">

            </div>

            <div class="mySlides fade">
                <img src="../Resources/Carrusel4.jpg" style="width:100%">

            </div>


            <!-- Next and previous buttons -->
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>

        <!-- The dots/circles -->
        <div style="text-align:center">
            <span class="dot" onclick="currentSlide(1)"></span>
            <span class="dot" onclick="currentSlide(2)"></span>
        </div>
        <h1>Añadir a Favoritos</h1>
        <div class="add-container">

            <a href="@Url.Action("ViewFoodClient","Client")">
                <i class="fa-solid fa-circle-plus"></i>
            </a>


        </div>
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/swal/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/MenuCliente.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/79ebbbb4e2.js" crossorigin="anonymous"></script>
</body>
</html>

App/Views/Client/PerfilCliente.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/PerfilNutri.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <header class="header">
        <div class="logo">
            <div>
                <img src="../Resources/LogoCompletoBlanco.png" alt="">
            </div>
        </div>
        <nav class="navbar">
            <a href="@Url.Action("MenuCliente", "Client")" id="SignIn">Volver al menu</a>
        </nav>
    </header>
    <div class="perfil">
        <h1>Mi Perfil</h1>
    </div>

    <div class="info">
        <div class="labels">
            <p>Nombre</p>
            <p>Cedula</p>
            <p>Apellido</p>

            <p>Correo</p>
            <p>Edad</p>
        </div>
        <div class="info-content">
            <p id="nombreUsuario"></p>
            <p id="cedula"></p>
            <p id="apellido"></p>
    
            <p id="correo"></p>
            <p id="edad"></p>
        </div>
        <div class="btn-container ">
            <button id="btn-modify">Modificar Datos</button>
        </div>

    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/swal/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/PerfilClient.js" asp-append-version="true"></script>
</body>
</html>

App/Views/Client/UpdateUserCliente.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/CreateUser.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <header class="header">
        <div class="logo">
            <div>
                <img src="~/Resources/LogoCompletoBlanco.png" alt="">
            </div>
        </div>
        <nav class="navbar">
            <a href="@Url.Action("MenuCliente", "Client")" id="SignIn">Volver al menú</a>
        </nav>
    </header>


    <div class="contenedor">


        <main class="main-content">
            <div class="container-content">
                <h1>Edita tus Datos</h1>
                <h2>Por favor llena todos los espacios con la información correspondiente</h2>
                <div class="info-and-photo-container">
                    <div class="register-container">
                        <div class="form-row">
                            <div class="input-container">
                                <label>Nombre</label>
                                <input class="input required" id="nombreUsuario" type="text" name="brand" />
                            </div>
                            <div class="input-container">
                                <label>Apellido</label>
                                <input id="apellido" class="input required" type="text" name="portionHome" />
                            </div>

                        </div>
                        <div class="form-row">
                            <div class="input-container">
                                <label>Cédula</label>
                                <input class="input required" id="cedula" type="text" name="brand" />
                            </div>
                            <div class="input-container">
                                <label>Edad</label>
                                <input id="edad" class="input required" type="number" name="excFlour" />
                            </div>

                        </div>
                        <div class="form-row">

                            <div class="input-container">
                                <label>Correo electrónico</label>
                                <input id="correo" class="input required" type="text" name="exceDairySkim" />
                            </div>
                           
                        </div>

                    </div>
                </div>
                <div class="button">
                    <div class="btn-container">
                        <button id="btn-continue">Modificar</button>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/swal/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/UpdateUserClient.js" asp-append-version="true"></script>
</body>
</html>

App/Views/Client/ViewSpecificFoodClient.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/SpecificFood.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <header class="header">
        <div class="logo">
            <div>
                 <img src="~/Resources/LogoCompletoBlanco.png" alt="">
            </div>
        </div>
        <nav class="navbar">
            <a href="@Url.Action("Menu","Nutri")">Menú</a>
            <a href="@Url.Action("ViewFood","Nutri")">Productos</a>
        </nav>
    </header>
    <div class="containerSpecific">

        <div class="specificContentPhoto" id="photo">
        
        </div>
         <div class="specificContentInfo" id="info">
       
        </div>
         
    </div>
    <div class="button">
                    <div class="btn-container">
                        <button id="btn-modify">Agregar a favoritos</button>
                    </div>
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/swal/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/ViewSpecificFoodClient.js" asp-append-version="true"></script>
    

</body>
</html>

App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

App/Views/LandingPage/LandingPage.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/79ebbbb4e2.js" crossorigin="anonymous"></script>
    <link href="~/css/Landing.css" type="text/css" rel="stylesheet" />

</head>
<body>
    <header class="header">
        <div class="logo">
            <div>
                <img src="../Resources/LogoCompletoBlanco.png" alt="">
            </div>
        </div>
        <nav class="navbar">
            <a href ="@Url.Action("Login", "LandingPage")" id="SignIn">Iniciar sesión</a>
            <a href="@Url.Action("CreateUser", "LandingPage")" id="CreateUser">Crear Usuario</a>
        </nav>
    </header>
    <div class="bg">
        <img class="img-container" src="../Resources/img1.jpg" style="width:100%">
        <div class="text-inside-image">Come bien, vive mejor: tu camino hacia una vida más saludable</div>
    </div>
    <div class="container">
        <div class="block-atribute">
            <p class="text-center">Navegación Intuitiva</p>
            <i class="fa-solid fa-apple-whole icon"></i>
        </div>
        <div class="block-atribute">
            <p class="text-center">Contenido Científicamente Fundado</p>
            <i class="fa-solid fa-flask icon"></i>
        </div>
        <div class="block-atribute">
            <p class="text-center">Diseño Atractivo</p>
            <i class="fa-solid fa-object-group icon"></i>
        </div>
    </div>
    <footer class="footer">
        <div class="footer-content">
            <div class="footer-logo">
                <img src="../Resources/Logo.png" alt="Footer Logo">
            </div>
          
        </div>
       
        <div class="footer-bottom">
            <p>&copy; 2024 Nutri4U. All rights reserved.</p>
        </div>
    </footer>
       



</body>
</html>

App/Views/Nutri/CreateFood.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/CreateFood.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <header class="header">
        <div class="logo">
            <div>
                <img src="../Resources/LogoCompletoBlanco.png" alt="">
            </div>
        </div>
        <nav class="navbar">
            <a href="@Url.Action("Menu", "Nutri")" id="SignIn">Volver al menú</a>
            <a href="@Url.Action("ViewFood", "Nutri")" id="SignIn">Comidas</a>
        </nav>
    </header>


    <div class="contenedor">


        <main class="main-content">
            <div class="container-content">
                <h1>Registra Un Nuevo Alimento </h1>
                <div class="info-and-photo-container">
                            <div class="register-container">
                                <div class="form-row">
                                    <div class="input-container">
                                        <label>Name</label>
                                        <input class="input required" id="txt-name" type="text" name="brand" />
                                    </div>
                                    <div class="input-container">
                                        <label>Marca</label>
                                        <input class="input required" id="txt-brand" type="text" name="brand" />
                                    </div>
                                  
                                    <div class="input-container">
                                        <label>Categoria</label>
                                        <select class="input required" id="categoryType" name="categoryType">
                                            <option id="" value=""></option>
                                            <option id="catCereal" value="Cereales">Cereales</option>
                                            <option id="catSalsa" value="Salsas y aderezos">Salsas y aderezos</option>
                                            <option id="catCarne" value="Carnes y Mariscos Enlatados">Carnes y Mariscos Enlatados</option>
                                            <option id="catPastas" value="Pastas">Pastas</option>
                                            <option id="catUntables" value="Untables">Untables</option>
                                            <option id="catVegetales" value="Vegetales enlatados">Vegetales enlatados</option>
                                            <option id="catAceites" value="Aceites y grasas">Aceites y grasas</option>
                                            <option id="catAzucar" value="Azúcar y substitutos">Azúcar y substitutos</option>
                                            <option id="catRefrescos" value="Gaseosas y refrescos">Gaseosas y refrescos</option>
                                            <option id="catEnergeticas" value="Bebidas Energéticas">Bebidas Energéticas</option>
                                            <option id="catHelados" value="Helados">Helados</option>
                                            <option id="catEmbutidos" value="Embutidos">Embutidos</option>
                                            <option id="catQuesos" value="Quesos">Quesos</option>
                                            <option id="catMantequilla" value="Mantequillas y margarinas">Mantequillas y margarinas</option>
                                            <option id="catLeche" value="Leche">Leche</option>
                                            <option id="catYogur" value="Yogur">Yogur</option>
                                            <option id="catPan" value="Pan y tortillas">Pan y tortillas</option>
                                        </select>
                                    </div>
                                    <div class="input-container">
                                        <label>Porcion en gramos</label>
                                <input id="portionGrams" class="input required" type="number" name="portionGrams" />
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="input-container">
                                        <label>Porcion Casera</label>
                                <input id="portionHome" class="input required" type="number" name="portionHome" />
                                    </div>
                                    <div class="input-container">
                                        <label>IntercambioHarina</label>
                                <input id="excFlour" class="input required" type="number" name="excFlour" />
                                    </div>
                                    <div class="input-container">
                                        <label>Intercambio de Lacteo Descremado</label>
                                <input id="excDairySkim" class="input required" type="number" name="exceDairySkim" />
                                    </div>
                                    <div class="input-container">
                                        <label>Intercambio de Lacteo Semi Descremado</label>
                                <input id="excDairySemi" class="input required" type="number" name="excDairySemi" />
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="input-container">
                                        <label>Intercambio de Lacteo Entero</label>
                                <input id="excDairyWhole" class="input required" type="number" name="excDairyWhole" />
                                    </div>
                                    <div class="input-container">
                                        <label>Intercambio Azucar</label>
                                <input class="input required" id="excSugar" type="number" name="excSugar" />
                                    </div>
                                    <div class="input-container">
                                        <label>Intercambio de Grasa</label>
                                <input id="excFat" class="input required" type="number" name="excFat" />
                                    </div>
                                    <div class="input-container">
                                        <label>Intercambio de Carne Magra</label>
                                <input id="excLeanMeat" class="input required" type="number" name="excLeanMeat" />
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="input-container">
                                        <label>Intercambio de Carne Semi Magra</label>
                                <input id="excSemiLeanMeat" class="input required" type="number" name="excSemiLeanMeat" />
                                    </div>
                                    <div class="input-container">
                                        <label>Intercambio de Carne Grasa</label>
                                <input id="excFatMeat" class="input required" type="number" name="excFatMeat" />
                                    </div>
                                    <div class="input-container">
                                        <label>Intercambio de Leguminosa</label>
                                <input id="excLeguminous" class="input required" type="number" name="excLeguminous" />
                                    </div>
                                    <div class="input-container">
                                        <label>Intercambio Fruta</label>
                                <input id="excFruit" class="input required" type="number" name="excFruit" />
                                    </div>
                                </div>
                                <div class="form-row">
                 
                                    <div class="input-container">
                                        <label>Intercambio Vegetal</label>
                                        <input id="excVegetable" class="input required" type="number" name="excVegetable" />
                                    </div>
                                    <div class="input-container">
                                        <label>Libre</label>
                                        <select class="input required" id="excFree" name="excFree">
                                            <option id="" value=""></option>
                                    <option id="noLibre" value="1">Si</option>
                                            <option id ="esLibre"  value="0">No</option>
                                        </select>
                                    </div>
                                    <div class="input-container">
                                        <label>Url de la imagen</label>
                                        <input id="image" class="input required" type="text" name="image" />
                                    </div>
                                   
                                </div>

                            </div>
                </div>
                <div class="button">
                    <div class="btn-container">
                        <button id="btn-continue">Continuar</button>

                    </div>
                </div>
            </div>
        </main>
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/swal/dist/sweetalert2.all.min.js"></script>
   
    <script src="~/js/CreateFood.js" asp-append-version="true"></script>
</body>
</html>

App/Views/Nutri/Perfil.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/css/PerfilNutri.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <header class="header">
        <div class="logo">
            <div>
                <img src="../Resources/LogoCompletoBlanco.png" alt="">
            </div>
        </div>
        <nav class="navbar">
            <a href="@Url.Action("Menu", "Nutri")" id="SignIn">Volver al menu</a>
        </nav>
    </header>
    <div class="perfil">
        <h1>Mi Perfil</h1>
    </div>

    <div class="info">
        <div class="labels">
            <p>Nombre</p>
            <p>Cedula</p>
            <p>Apellido</p>
            <p>Correo</p>
            <p>Edad</p>
        </div>
        <div class="info-content">
            <p id="nombreUsuario"></p>
            <p id="cedula"></p>
            <p id="apellido"></p>
            <p id="correo"></p>
            <p id="edad"></p>
        </div>
        <div class="btn-container ">
            <button id="btn-modify">Modificar Datos</button>
        </div>
       
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/swal/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Perfil.js" asp-append-version="true"></script>
</body>
</html>